### ISSUE TITLE
1 . 好像不支持 多master  2.好像没有分片上传呢？

### ISSUE THREAD

**Issue by whaosoft** [Shuyun123/seaweedfs-java-client#13]
帮忙回答一下

**Comment by zhiyoucai** [comment]
1. 这个客户端基本上实现了官方给出的接口，但是我在接口里没有发现多master，不知道你这里说的多master具体指代什么？
2. 分片上传内容，SeaweedFS作者也是最近一段时间才补全了wiki。

**Comment by whaosoft** [comment]
嗯 
分片昨天我找了作者了 一起看看到时给你说说 你有群吗 微信的？ QQ也凑乎
多master是 现在咱们代码不只是可以填一个吗 现在我是3个master节点  用ng应该可以解决但我不想多一层

**Comment by zhiyoucai** [comment]
发邮件讨论，zq.works@hotmail.com

**Comment by whaosoft** [comment]
这谁的邮箱啊？ 这太不方便了 没 别的方式了吗

**Comment by zhiyoucai** [comment]
首先我不是原作者，我只是最近在用seaweedfs，找了个client，发现很久没有更新了，自己fork了一份在更新。
其次我们公司是打算在此基础上更改的，我也算是听取一下有效意见，顺便参考别人的思路。
不接受就算了。

**Comment by whaosoft** [comment]
你有微信吗 这原作者 好像不是weed的作者啊 好像我还发现点问题

**Comment by ghostsf** [comment]
多master host 用逗号分隔 就可以了
